import type { Metadata } from "next";
import "./globals.css";
import { EnvScript } from "@daniel-rose/envex/script";
import { EnvexProvider } from "@daniel-rose/envex";
import {getPublicEnv, getEnvByName} from "@daniel-rose/envex/server";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialEnv = await getPublicEnv()
  const barEnv = await getEnvByName('BAR')

  return (
    <html lang="en">
      <body>
        <EnvScript />
        <EnvexProvider initialEnv={initialEnv}>
          <div data-testid="server-env">BAR: {barEnv}</div>
          {children}
        </EnvexProvider>
      </body>
    </html>
  );
}
