import type { Metadata } from "next";
import "./globals.css";
import { EnvScript } from "@daniel-rose/envex/script";
import { EnvexProvider } from "@daniel-rose/envex";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <EnvScript />
        <EnvexProvider>
          {children}
        </EnvexProvider>
      </body>
    </html>
  );
}
